### ISSUE TITLE
Selenium Installation

### ISSUE THREAD

**Issue by cry0genic** [vital987/chrome-novnc#10]
Hey, I wanted to use selenium to control the chromium instance that is launched. However, I tried a variety of ways like changing the base image, but none let me install Selenium in the docker container.

Can you maybe guide me how can I implement a way to control the chromium instance using selenium with the current setup you have?

Many thanks!

**Comment by vital987** [comment]
You can install Selenium Grid into the container and operate it from your host PC via container's IP address.

Reference: https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/#:~:text=Selenium%20lets%20you%20automate%20browsers,sometimes%20as%20an%20end%2Dnode.

**Comment by cry0genic** [comment]
Thanks! I'll try this out and get back to you.

PS: I already tried adding py3-pip to the add apk command, and then run pip3 install in the Dockerfile, but it was not letting me do so, hence I reached out.

**Comment by cry0genic** [comment]
Hey @vital987, so I tried installing Selenium Grid, but even after doing so, I'm facing some issues. If you do get some free time, can we maybe hop on a call or G-Meet? I've been struggling to implement the desired functionality for the past 1-2 days and would really appreciate some help.

Do let me know if it is possible, otherwise, it is fine.

Thanks

**Comment by cry0genic** [comment]
So I was able to install Selenium Grid in the container. Here's the changes I've made, but I'm unable to control Chromium via this. Let me know if you can find any mistake.

**config/supervisor/7-selenium.conf**:
```
[program:Selenium]
command=java -jar /opt/selenium/selenium-server-standalone.jar
priority=4
autorestart=true
stderr_logfile=/var/log/selenium.err.log
```



**docker-compose.yml**:
```
version: '3.4'

services:
  chrome-novnc:
    container_name: chrome-novnc
    environment:
      - VNC_PASS=${VNC_PASS-interface}
      - VNC_TITLE=${VNC_TITLE-Chromium}
      - VNC_SHARED=${VNC_SHARED-false}
      - VNC_RESOLUTION=${VNC_RESOLUTION-1280x720}
      - PORT=8080
    image: vital987/chrome-novnc:latest
    ports:
      - "${HOST_PORT-8080}:8080/tcp"
      - "4444:4444/tcp"
    restart: always



**Dockerfile**:
```dockerfile
FROM alpine:3.19.1

LABEL AboutImage "Alpine_Chromium_NoVNC"


ENV	VNC_PASS="interface" \

	VNC_TITLE="Chromium" \

	VNC_RESOLUTION="1280x720" \

	VNC_SHARED=false \

	DISPLAY=:0 \

	NOVNC_PORT=$PORT \
	PORT=8080 \

	NO_SLEEP=false \
#Locale
	LANG=en_US.UTF-8 \
	LANGUAGE=en_US.UTF-8 \
	LC_ALL=C.UTF-8 \
	TZ="Asia/Kolkata"

COPY assets/ /

RUN apk add --no-cache openjdk11-jre
RUN mkdir /opt/selenium	
RUN wget -q "https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar" -O /opt/selenium/selenium-server-standalone.jar
RUN wget -q "https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip" -O /tmp/chromedriver.zip \
		&& unzip /tmp/chromedriver.zip -d /opt/selenium \
		&& rm /tmp/chromedriver.zip \
		&& chmod 755 /opt/selenium/chromedriver

RUN	apk update && \
	apk add --no-cache tzdata ca-certificates supervisor curl wget openssl bash python3 py3-requests sed unzip xvfb x11vnc websockify openbox chromium nss alsa-lib font-noto font-noto-cjk && \

	openssl req -new -newkey rsa:4096 -days 36500 -nodes -x509 -subj "/C=IN/O=Dis/CN=www.google.com" -keyout /etc/ssl/novnc.key -out /etc/ssl/novnc.cert > /dev/null 2>&1 && \

	cp /usr/share/zoneinfo/$TZ /etc/localtime && \
	echo $TZ > /etc/timezone && \

	apk del build-base curl wget unzip tzdata openssl && \
	rm -rf /var/cache/apk/* /tmp/*
ENTRYPOINT ["supervisord", "-l", "/var/log/supervisord.log", "-c"]

CMD ["/config/supervisord.conf"]
``` 

**app.py**

```python
from flask import Flask, jsonify
from selenium import webdriver
import time

app = Flask(__name__)

@app.route('/sel', methods=['GET'])
def run_selenium():
    options = webdriver.ChromeOptions()
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--disable-gpu')
    driver = webdriver.Remote(
        command_executor='http://localhost:4444/wd/hub',
        options=options
    )
    driver.get('https://www.facebook.com')
    time.sleep(15)
    driver.quit()
    return jsonify({'status': 'success'})

@app.route('/hello', methods=['GET'])
def hello_world():
    return 'Hello, world!'

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
```

**Comment by vital987** [comment]
https://github.com/vital987/chrome-novnc/tree/selenium

Works with: 
```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time

grid_server = 'http://x.x.x.x:4444/wd/hub'

chrome_options = Options()
chrome_options.add_argument('--no-sandbox')

driver = webdriver.Remote(
    command_executor=grid_server,
    options=chrome_options
)

driver.get('https://www.facebook.com')

time.sleep(3)

driver.quit()

```

One of the issue in your code is the installation of the chromedriver. The installed version is unsupported by alpine linux maybe due absence of glibc. You should install is via ```apk add --no-cache chromium-chromedriver```

**Comment by cry0genic** [comment]
Hey, thanks! Two things:
1. This does not work locally for me on a M2 MacBook.
2. However, I tried this on a G-Cloud VM instance, and it worked perfectly there.

Thanks, I'm closing the issue now.

PS: Seems like I tried most things locally, so even if I had tried something correct, it would've still not worked.

**Comment by vital987** [comment]
> 1. This does not work locally for me on a M2 MacBook.

M2 is ARM64 while the image is AMD64 based, try using ```--platform linux/amd64``` argument.

> PS: Seems like I tried most things locally, so even if I had tried something correct, it would've still not worked.

I can be sure of chromedriver in your code not working due to me suffering from same issue while working on modifications.

**Comment by cry0genic** [comment]
Hey @vital987, not an issue per se but when I'm running large Selenium tests and stream it via VNC, the automation chrome browser that opens crashes randomly. I was wondering if you have any idea why this might be happening?

I already have a VM with 8GB of memory, and a good internet connection as well.

Thanks once again!
