### ISSUE TITLE
Server Disconnected: Target Closed (1000)

### ISSUE THREAD

**Issue by cry0genic** [vital987/chrome-novnc#13]
Hey @vital987, I want to view the instance in two separate browsers. However, if one tab is active, the other tab does not let me view the noVNC browser. Is there a workaround for this?

Thanks!

**Comment by vital987** [comment]
Try setting VNC_SHARED environment variable to true i.e. ```VNC_SHARED=true```

**Comment by cry0genic** [comment]
Hey @vital987, I already tried this. I've changed it both in the `Dockerfile` as well as the `docker-compose.yml` file.

```#VNC Shared Mode
  VNC_SHARED=true \
```

```
VNC_SHARED=${VNC_SHARED-true}
```

**Comment by cry0genic** [comment]
Hey @vital987, following up, do let me know if you can help me out here.

Thanks!

**Comment by cry0genic** [comment]
Hey @vital987, if you're free now do check this issue out. Thanks!

**Comment by cry0genic** [comment]
This fixed it:
```
[program:VNC]
command=bash -c 'sed -i "s/\$DESKTOP/$VNC_TITLE/g" /opt/novnc/index.html && if [ "$VNC_SHARED" = "false" ]; then x11vnc -storepasswd $VNC_PASS /config/.xpass && x11vnc -usepw -rfbport 5900 -rfbauth /config/.xpass -geometry $VNC_RESOLUTION -forever -alwaysshared -permitfiletransfer -noxrecord -noxfixes -noxdamage -dpms -bg -desktop $VNC_TITLE; else x11vnc -storepasswd $VNC_PASS /config/.xpass && x11vnc -usepw -rfbport 5900 -rfbauth /config/.xpass -geometry $VNC_RESOLUTION -forever -shared -alwaysshared -permitfiletransfer -bg -desktop $VNC_TITLE; fi'
startsecs=0
autorestart=unexpected
stderr_logfile=/var/log/x11vnc.stderr.log
priority=3

```

**Comment by alperengunes** [comment]
@cry0genic How did you solve it?

**Comment by alperengunes** [comment]
/chrome-novnc/assets/config/supervisor -> vnc.conf ?
