### ISSUE TITLE
Typing Problem

### ISSUE THREAD

**Issue by mmwong1984** [vital987/chrome-novnc#4]
Hi!
I am a people from Taiwan.
I know docker do not support chinese and I solve it by installing fonts
BUT
I cannot type Chinese, even I paste the characters 
(Device on iPad)
Wish that you can solve it
It is a great project

**Comment by mmwong1984** [comment]
ok

**Comment by mmwong1984** [comment]
Wait, I think you misunderstood my question. I am asking that I cannot "type" not cannot "show" Chinese
@vital987

**Comment by vital987** [comment]
Okay, I'll look into it.

**Comment by vital987** [comment]
You can install [Google Input Tools](https://chromewebstore.google.com/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab) extension in chrome to achieve it.
