### ISSUE TITLE
Setup Guide

### ISSUE THREAD

**Issue by thedavidweng** [vital987/chrome-novnc#5]
Hello, I have set up the VNC_PASS environment variable, but I don't know where to enter the password after opening it. There is only one navigation bar on the interface, and it shows that the server is not connected, and there is nothing else.

**Comment by vital987** [comment]
The password prompt comes after connecting to the VNC server, for some reason the noVNC ain't connecting to the VNC server, normally it should connect, retry following steps in readme.
