### ISSUE TITLE
Unexpected Logs

### ISSUE THREAD

**Issue by steveji2021** [vital987/chrome-novnc#7]
The web interface works fine, but there are error logs always creating. Why’s that?

![image](https://github.com/vital987/chrome-novnc/assets/88028845/23558c1e-eafd-40bd-b7ad-2b7b27c987ab)

**Comment by vital987** [comment]
Also the script is erroring with exit code 1 which is unexpected. I'll look into the issue.

**Comment by steveji2021** [comment]
I’m just running it in Docker, not deploying it to Heroku. So I didn’t create these variables.

**Comment by vital987** [comment]
Try setting NO_SLEEP variable to 0

**Comment by steveji2021** [comment]
Same logs as before.

**Comment by vital987** [comment]
Fixed
