### ISSUE TITLE
 how to automatically load specified plugins at startup

### ISSUE THREAD

**Issue by BG5T** [vital987/chrome-novnc#8]
Hello, big brother, how to automatically load specified plugins at startup? Looking forward to your reply. Thank you very much for your project.

**Comment by vital987** [comment]
If you're referring to extensions, there isn't a direct way to preload them. However, there's a method for loading unpacked extensions, though it's not secure. An alternative approach is to store your Chromium user data in a Docker volume, which ensures that your browser state persists across restarts.
