### ISSUE TITLE
Chinese characters on webpages are displaying as squares

### ISSUE THREAD

**Issue by zhu0823** [vital987/chrome-novnc#9]
It seems like after updating to the latest version, Chinese characters on webpages are displaying as squares. This issue wasn't present before version 0.12.0.

- The environment variables I configured in Docker：
PATH				/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VNC_PASS			xxxxxx
VNC_TITLE			VNC
VNC_RESOLUTION	1920×1080
VNC_SHARED		    0
DISPLAY				:0
NOVNC_PORT		9870
PORT				9870
LANG				zh_CN.UTF-8
LANGUAGE			zh_CN.UTF-8
LC_ALL				C.UTF-8
TZ					Asia/Shanghai
NO_SLEEP			false

- screenshot：
<img width="1323" alt="iShot_2024-05-14_18 30 41" src="https://github.com/vital987/chrome-novnc/assets/13061892/96821960-3e58-41ea-ac27-b56fca089915">

**Comment by vital987** [comment]
Fixed
